# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_authors_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
